on:
  push:
   branches:
    - master
jobs:
  update_readme:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: update
        run: | 
          python main.py
          git config user.name mrgold92
          git config user.email davids1_4@hotmail.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update readme"
          git push origin master
          git pull 
        
